//go:build !try

// Code generated by github.com/goghcrow/go-try DO NOT EDIT.
//go:generate go install github.com/goghcrow/go-try/cmd/trygen@main
//go:generate trygen
package example

import (
	. "github.com/goghcrow/go-try/rt"
	"io"
	"os"
)

//goland:noinspection GoUnhandledErrorResult
func CopyFile(src, dst string) (err error) {
	𝘃𝗮𝗹𝟭, 𝗲𝗿𝗿𝟮 := os.Open(src)
	if 𝗲𝗿𝗿𝟮 != nil {
		return 𝗲𝗿𝗿𝟮
	}
	r := 𝘃𝗮𝗹𝟭
	defer r.Close()
	𝘃𝗮𝗹𝟯, 𝗲𝗿𝗿𝟰 := os.Create(dst)
	if 𝗲𝗿𝗿𝟰 != nil {
		return 𝗲𝗿𝗿𝟰
	}
	w := 𝘃𝗮𝗹𝟯
	defer func() {
		w.Close()
		if err != nil {
			os.Remove(dst)
		}
	}()
	_, 𝗲𝗿𝗿𝟱 := io.Copy(w, r)
	if 𝗲𝗿𝗿𝟱 != nil {
		return 𝗲𝗿𝗿𝟱
	}
	Ø()
	𝗲𝗿𝗿𝟲 := w.Close()
	if 𝗲𝗿𝗿𝟲 != nil {
		return 𝗲𝗿𝗿𝟲
	}
	Ø()
	return nil
}
