//go:build !try

// Code generated by github.com/goghcrow/go-try DO NOT EDIT.
package example

import (
	"fmt"
	"io"
	"log"
	"os"
	"strconv"
)

func printSum1(a, b string) error {
	𝘃𝗮𝗹𝟭, 𝗲𝗿𝗿𝟭 := strconv.Atoi(a)
	if 𝗲𝗿𝗿𝟭 != nil {
		return 𝗲𝗿𝗿𝟭
	}
	x := 𝘃𝗮𝗹𝟭
	𝘃𝗮𝗹𝟮, 𝗲𝗿𝗿𝟮 := strconv.Atoi(b)
	if 𝗲𝗿𝗿𝟮 != nil {
		return 𝗲𝗿𝗿𝟮
	}
	y := 𝘃𝗮𝗹𝟮
	fmt.Println("result:", x+y)
	return nil
}
func printSum2(a, b string) error {
	𝘃𝗮𝗹𝟭, 𝗲𝗿𝗿𝟭 := strconv.Atoi(a)
	if 𝗲𝗿𝗿𝟭 != nil {
		return 𝗲𝗿𝗿𝟭
	}
	𝘃𝗮𝗹𝟮, 𝗲𝗿𝗿𝟮 := strconv.Atoi(b)
	if 𝗲𝗿𝗿𝟮 != nil {
		return 𝗲𝗿𝗿𝟮
	}
	fmt.Println("result:", 𝘃𝗮𝗹𝟭+𝘃𝗮𝗹𝟮)
	return nil
}
func parseHexdump(text string) (_ []byte, _ error) { ; return }
func localMain() error {
	𝘃𝗮𝗹𝟭, 𝗲𝗿𝗿𝟭 := io.ReadAll(os.Stdin)
	if 𝗲𝗿𝗿𝟭 != nil {
		return 𝗲𝗿𝗿𝟭
	}
	hex := 𝘃𝗮𝗹𝟭
	𝘃𝗮𝗹𝟮 := string(hex)
	𝘃𝗮𝗹𝟯, 𝗲𝗿𝗿𝟮 := parseHexdump(𝘃𝗮𝗹𝟮)
	if 𝗲𝗿𝗿𝟮 != nil {
		return 𝗲𝗿𝗿𝟮
	}
	data := 𝘃𝗮𝗹𝟯
	_, 𝗲𝗿𝗿𝟯 := os.Stdout.Write(data)
	if 𝗲𝗿𝗿𝟯 != nil {
		return 𝗲𝗿𝗿𝟯
	}

	return nil
}
func main() {
	if err := localMain(); err != nil {
		log.Fatal(err)
	}
}
