//go:build !try

// Code generated by github.com/goghcrow/go-try DO NOT EDIT.
package test

import (
	"fmt"
)

func named_error() (a int, err error) {
	_, 𝗲𝗿𝗿𝟭 := ret1Err[bool]()
	if 𝗲𝗿𝗿𝟭 != nil {
		err = 𝗲𝗿𝗿𝟭
		return
	}
	a = 42
	return
}
func catch_and_log() (a int, err error) {
	defer func() {
		if err != nil {
			a = -1
			fmt.Println(err)
		}
	}()
	_, 𝗲𝗿𝗿𝟭 := ret1Err[bool]()
	if 𝗲𝗿𝗿𝟭 != nil {
		err = 𝗲𝗿𝗿𝟭
		return
	}
	a = 42
	return
}
func error_wrapping() (a int, err error) {
	defer handleErrorf(&err, "something wrong")
	_, 𝗲𝗿𝗿𝟭 := ret1Err[bool]()
	if 𝗲𝗿𝗿𝟭 != nil {
		err = 𝗲𝗿𝗿𝟭
		return
	}
	a = 42
	return
}
func handleErrorf(err *error, format string, args ...interface{}) {
	if *err != nil {
		*err = fmt.Errorf(format+": %v", append(args, *err)...)
	}
}
