//go:build !try

// Code generated by github.com/goghcrow/go-try DO NOT EDIT.
package test

func map_index() error {
	{
		var m map[int]int
		𝘃𝗮𝗹𝟭, 𝗲𝗿𝗿𝟭 := ret1Err[int]()
		if 𝗲𝗿𝗿𝟭 != nil {
			return 𝗲𝗿𝗿𝟭
		}
		m[𝘃𝗮𝗹𝟭] = 1
	}
	{
		{
			var m map[int]int
			𝘃𝗮𝗹𝟮, 𝗲𝗿𝗿𝟮 := ret1Err[int]()
			if 𝗲𝗿𝗿𝟮 != nil {
				return 𝗲𝗿𝗿𝟮
			}
			println(m[0], 𝘃𝗮𝗹𝟮)
		}
		{
			var m map[any]int
			𝘃𝗮𝗹𝟯 := m[0]
			𝘃𝗮𝗹𝟰, 𝗲𝗿𝗿𝟯 := ret1Err[int]()
			if 𝗲𝗿𝗿𝟯 != nil {
				return 𝗲𝗿𝗿𝟯
			}
			println(𝘃𝗮𝗹𝟯, 𝘃𝗮𝗹𝟰)
		}
	}
	{
		var m map[int]int
		𝘃𝗮𝗹𝟱 := func() int { ; println("called"); return 0 }()
		𝘃𝗮𝗹𝟲, 𝗲𝗿𝗿𝟰 := ret1Err[int]()
		if 𝗲𝗿𝗿𝟰 != nil {
			return 𝗲𝗿𝗿𝟰
		}
		println(m[𝘃𝗮𝗹𝟱], 𝘃𝗮𝗹𝟲)
	}
	return nil
}
