//go:build !try

// Code generated by github.com/goghcrow/go-try DO NOT EDIT.
package test

type myErr struct{}

func (e myErr) Error() string { ; return "" }
func try_ret_myerr() (err error) {
	𝘃𝗮𝗹𝟭, 𝗲𝗿𝗿𝟭 := func() (int, error) { ; return 42, myErr{} }()
	if 𝗲𝗿𝗿𝟭 != nil {
		err = 𝗲𝗿𝗿𝟭
		return
	}
	_ = 1 + 𝘃𝗮𝗹𝟭
	return nil
}
