//go:build !try

// Code generated by github.com/goghcrow/go-try DO NOT EDIT.
package test

import . "github.com/goghcrow/go-try/rt"

func xxx() (err error) {
	for a := 1; a > 0; {
		𝗽𝗼𝘀𝘁𝟭 := func() (_ E𝗿𝗿𝗼𝗿) {
			𝘃𝗮𝗹𝟭, 𝗲𝗿𝗿𝟭 := ret1Err[int]()
			if 𝗲𝗿𝗿𝟭 != nil {
				return 𝗲𝗿𝗿𝟭
			}
			a = 𝘃𝗮𝗹𝟭
			return
		}
		a := 42
		_ = a
		if true {
			𝗲𝗿𝗿𝟭 := 𝗽𝗼𝘀𝘁𝟭()
			if 𝗲𝗿𝗿𝟭 != nil {
				err = 𝗲𝗿𝗿𝟭
				return
			}
			continue
		}
		println(a)
		𝗲𝗿𝗿𝟮 := 𝗽𝗼𝘀𝘁𝟭()
		if 𝗲𝗿𝗿𝟮 != nil {
			err = 𝗲𝗿𝗿𝟮
			return
		}
	}
	return nil
}
