package rewriter

const (
	defaultFileSuffix = "try"
	defaultBuildTag   = "try"

	pkgTryPath = "github.com/goghcrow/go-try"
	pkgRTPath  = "github.com/goghcrow/go-try/rt" // 𝙧𝙩

	labelPrefix        = "L_"
	valIdentPrefix     = "val"
	errIdentPrefix     = "err"
	valZeroIdentPrefix = "zero"

	fileComment = `//go:build !%s

// Code generated by github.com/goghcrow/go-try DO NOT EDIT.
`
)

var (
	funcTryNames = []string{"Try0", "Try", "Try2", "Try3"}
	tupleNames   = []string{"Ø", "I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X"}
)

func retCntOfTryFn(tryFn string) int {
	for i, name := range funcTryNames {
		if tryFn == name {
			return i + 1 /*err*/
		}
	}
	panic("illegal try func: " + tryFn)
}
